name: smartos
version: '1.0.0'
summary: Smart Home Operating System
description: |
  SmartOS is a modern, user-friendly smart home operating system built on top of Home Assistant.
  It focuses on simplicity, security, and scalability while maintaining full local control.

grade: stable
confinement: strict
base: core22

apps:
  smartos:
    command: bin/smartos-launch
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - bluetooth-control
      - hardware-observe
      - system-observe
      - home

parts:
  smartos:
    plugin: python
    python-packages:
      - pip
      - setuptools
      - wheel
    source: ../../../engine
    requirements:
      - ../../../engine/requirements.txt
    override-build: |
      # Copy SmartOS core files
      cp -r ../../../core $SNAPCRAFT_PART_BUILD/

      # Install Python dependencies
      pip install -r requirements.txt

      # Create launch script
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat > $SNAPCRAFT_PART_INSTALL/bin/smartos-launch << 'EOF'
      #!/bin/bash
      export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages"
      cd $SNAP
      exec python3 -m homeassistant --config $HOME/.smartos/config
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/smartos-launch

  config:
    plugin: dump
    source: ../../../core/config
    organize:
      configuration.yaml: share/smartos/configuration.yaml
